### ISSUE TITLE
Is there a callback for after png/pdf generated?

### ISSUE THREAD

**Issue by daryld212** [Studiosity/grover#140] opened 2021-11-10 01:49 UTC
Is there a callback that can be run after Grover has created a new screenshot?

Currently, this often creates a "Connection Timeout" error. How can I run the update command AFTER the screenshot has been generated?

    new_img = Grover.new(html, html_options).to_png
    image = Base64.encode64(new_img)

    # Run this AFTER screenshot has been generated
    record.update!(image_uri: "data:image/png;base64,#{image.html_safe}")

**Comment by abrom** [comment] 2021-11-10 02:46
Difficult to say what the problem is without more details about what the timeout relates to.. 

There are options to increase the timeouts for how Puppeteer/Chromium will behave, but that would depend on what you have timing out 😉. There are multiple "connections" going on, even if you are passing static HTML in. Your HTML may be referencing external resources. Those resources may have time/resource constraints, or connectivity issues. You've also got the connection between Grover and Puppeteer/Chromium. It uses the DevTools Protocol via a local TCP port, so there could be issues there, or simply issues with Chromium starting (and thus being connected to!). 

Can you elaborate? Does it timeout all of the time? What if you just pass in something simple like:
```
img = Grover.new('hey').to_png
```
What steps have you taken to figure out WHAT is causing the timeout?

In terms of your question of callbacks.. no, there are none. The generation of a PDF or screenshot (PNG/JPEG etc) is synchronous, thus the call to `update!` WILL happen after the screenshot has been generated.

However given the description of your problem, I don't think an asynchronous generation would help. Something is exceeding some sort of prescribed limit for time allowed to achieve some behaviour. Having the generation asynchronous wouldn't change that.

**Comment by daryld212** [comment] 2021-11-10 04:33
Thanks for the detailed reply, you're absolutely right.

After some testing with the update command, it definitely runs after Grover has finished generating the screenshot. This command itself is within a Sidekiq background worker, that's where the timeout is coming from.

I updated the worker to run:

    img = Grover.new('hey').to_png

And the timeout error is still being triggered. Assuming now it's an issue with Sidekiq, and I'll need to allow more time to the connection than the 5-second default. Here is the error message:

    WARN: ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds
    (waited 5.005 seconds); all pooled connections were in use

Originally assumed that because it is ActiveRecord error, that the update command was started and couldn't finish running while it waited for Grover to generate the image - taking more than 5 seconds. I could extend the timeout to maybe 10 seconds, but there's a connection leak somewhere.

**Comment by abrom** [comment] 2021-11-10 07:04
Right. Yes that sounds very much like a database connection related issue (ActiveRecord) and not Grover 🙂

I'm no expert with the use of Sidekiq, but a 5 second database connection timeout already seems quite large. It suggests you have some other sort of configuration issue at play here. In any case, it seems safe to close this issue

**Closed by abrom** 2021-11-10 07:04 UTC
